hi! link javaFunction gruvboxyellow
hi! link javaOperator gruvboxblue
hi! link javaDelimiter gruvboxgray
hi! link javaSpecial gruvboxblue
hi! link javaIdentifier gruvboxfg1
hi! link javaType gruvboxorange
hi! link javaStorageClass gruvboxred
hi! link javaStructure gruvboxred
hi! link javaPackagePath gruvboxblue
