#!/usr/bin/bash
function run () {
choice=$({ echo "SSID:RATE:BARS:SECURITY" & 
  nmcli -t d wifi list --rescan $1; } | 
  awk -F ":" '
  $1 == "SSID" {print $1","$2","$3","$4}\
  $1 != "SSID" && $8 != "" {print $8","$11","$13","$14}' | 
  column -t -s ',' -o $'\t' | 
  rofi -dmenu -p "Search" -selected-row 1)

  IFS=$'\t'
  read -ra ADDR <<< "$choice"
  IFS=' '

  ssid=$(echo "${ADDR[0]}" | xargs)
  
  if [[ $ssid = "SSID" ]]; then
    run "no"
  elif [[ $ssid = "" ]]; then
    exit 0
  else 
    connect "$ssid"
  fi
}

function connect () {
  pass=$(rofi -dmenu -password -theme "$HOME/.config/rofi/themes/input.rasi" -p "Passkey:")
  if [[ $pass = "" ]]; then 
    run "no"
  else
    echo "Connecting with SSID:$1..." | rofi -dmenu -theme "$HOME/.config/rofi/themes/text.rasi" &
    pid=$!
    out=$(nmcli dev wifi connect "$1" password "$pass" | grep -c "successfully")
    kill -9 $pid
    if [[ $out = "1" ]]; then
      echo "Connected!" | rofi -dmenu -theme "$HOME/.config/rofi/themes/text.rasi"
    else 
      echo "Error, could not connect" | rofi -dmenu -theme "$HOME/.config/rofi/themes/text.rasi"
    fi
  fi
}

run "yes"
